---
- name: Crear una VM con Vagrant/Ansible
  hosts: localhost
  vars:
    box: geerlingguy/ubuntu1804 
    path: $HOME/vagrant_dinamic_deploy/Vagrantfile    
  
  tasks:
    - name: Crea el Vagrantfile
      command: vagrant init "{{ box }}" creates=Vagrantfile

    - name: Modifica el Vagrantfile para usar con WSL
      lineinfile:
        path: "{{ path }}"
        insertbefore: '^end'
        line: |
          config.vm.synced_folder ".", "/vagrant", disabled: true
          config.vm.network "forwarded_port", guest: 80, host: 8080 
    
    - name: Inicia la VM
      command: vagrant up


